steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "frontend",
        "--source",
        ".",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--project",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
