import { jsPDF } from 'jspdf';
import React, { useState } from 'react';
import RippleButton from '../RippleButton';

/* ------------------------------------------------------------------ */
/* Brand palette (from your Tailwind/theme config)                     */
/* ------------------------------------------------------------------ */

const BRAND = {
    primary100: '#D4CCFB',
    primary200: '#A694F3',
    primary300: '#755BEA',
    ink: '#1E1B2E', // near-black with a violet tint, for headings
    body: '#4B4560', // body text
    muted: '#8B85A3', // secondary/meta text
    border: '#E7E2FB',
    tint: '#F7F5FE', // very light card background
    white: '#FFFFFF',
    success: '#1F9D6C',
};

const PAGE = {
    width: 210,
    height: 297,
    margin: 16,
    contentWidth: 210 - 16 * 2,
};

/* ------------------------------------------------------------------ */
/* Small helpers                                                       */
/* ------------------------------------------------------------------ */

function hexToRgb(hex) {
    const clean = hex.replace('#', '');
    const bigint = parseInt(clean, 16);
    return [(bigint >> 16) & 255, (bigint >> 8) & 255, bigint & 255];
}

function setFill(doc, hex) {
    const [r, g, b] = hexToRgb(hex);
    doc.setFillColor(r, g, b);
}

function setText(doc, hex) {
    const [r, g, b] = hexToRgb(hex);
    doc.setTextColor(r, g, b);
}

function setDraw(doc, hex) {
    const [r, g, b] = hexToRgb(hex);
    doc.setDrawColor(r, g, b);
}

/** Loads an image from a public path (e.g. '/logo.png') as a base64 data URL. */
async function loadImageAsDataURL(path) {
    const res = await fetch(path);
    if (!res.ok) throw new Error(`Could not load image at ${path}`);
    const blob = await res.blob();
    const dataUrl = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
    });
    const { width, height } = await new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => resolve({ width: img.width, height: img.height });
        img.onerror = reject;
        img.src = dataUrl;
    });
    return { dataUrl, width, height };
}

/** Formats an ISO/RFC date string into something readable. */
function formatDate(dateStr) {
    if (!dateStr) return '—';
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    return d.toLocaleString(undefined, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
}

function formatDuration(seconds) {
    if (!seconds && seconds !== 0) return '—';
    const s = Math.round(seconds);
    const m = Math.floor(s / 60);
    const rem = s % 60;
    return `${m}m ${rem}s`;
}

/* ------------------------------------------------------------------ */
/* PDF builder                                                         */
/* ------------------------------------------------------------------ */

export async function exportMomentToPDF(currentMoment, options = {}) {
    const {
        logoPath = '/new-crips-ai-logo-black-resize.png',
        appName = 'CrispAI',
        fileName,
    } = options;

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    let cursorY = 0;
    let page = 1;

    let logoData = null;
    try {
        logoData = await loadImageAsDataURL(logoPath);
    } catch (err) {
        console.warn('[exportMomentToPDF] logo not loaded:', err.message);
    }

    /* ---------- reusable low-level drawing pieces ---------- */

    const drawFooter = () => {
        setDraw(doc, BRAND.border);
        doc.setLineWidth(0.2);
        doc.line(PAGE.margin, PAGE.height - 14, PAGE.width - PAGE.margin, PAGE.height - 14);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        setText(doc, BRAND.muted);
        doc.text(`Generated by ${appName}`, PAGE.margin, PAGE.height - 9);
        doc.text(
            `Page ${page}`,
            PAGE.width - PAGE.margin,
            PAGE.height - 9,
            { align: 'right' }
        );
    };

    const newPage = () => {
        drawFooter();
        doc.addPage();
        page += 1;
        cursorY = PAGE.margin;
    };

    /** Ensures there's room for `h` mm of content; adds a page if not. */
    const ensureSpace = (h) => {
        if (cursorY + h > PAGE.height - 20) newPage();
    };

    const sectionTitle = (label) => {
        ensureSpace(12);
        setFill(doc, BRAND.primary300);
        doc.roundedRect(PAGE.margin, cursorY, 1.4, 5, 0.7, 0.7, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        setText(doc, BRAND.ink);
        doc.text(label.toUpperCase(), PAGE.margin + 4, cursorY + 4.2);
        cursorY += 10;
    };

    const bodyText = (text, opts = {}) => {
        const { fontSize = 9.5, color = BRAND.body, lineHeight = 4.6, x = PAGE.margin, width = PAGE.contentWidth } = opts;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(fontSize);
        setText(doc, color);
        const lines = doc.splitTextToSize(text, width);
        lines.forEach((line) => {
            ensureSpace(lineHeight);
            doc.text(line, x, cursorY + lineHeight - 1.4);
            cursorY += lineHeight;
        });
    };

    /** Renders a rounded pill badge and returns its width so callers can chain. */
    const pill = (text, x, y, { bg = BRAND.tint, fg = BRAND.primary300, fontSize = 8 } = {}) => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(fontSize);
        const padX = 3;
        const textW = doc.getTextWidth(text);
        const w = textW + padX * 2;
        const h = 6;
        setFill(doc, bg);
        doc.roundedRect(x, y, w, h, h / 2, h / 2, 'F');
        setText(doc, fg);
        doc.text(text, x + padX, y + h / 2 + 1.4);
        return w;
    };

    /* ---------- cover header band ---------- */

    const drawCoverHeader = () => {
        setFill(doc, BRAND.primary300);
        doc.rect(0, 0, PAGE.width, 34, 'F');
        setFill(doc, BRAND.primary200);
        doc.triangle(PAGE.width * 0.55, 0, PAGE.width, 0, PAGE.width, 34, 'F');

        if (logoData) {
            try {
                const logoH = 10;
                const logoW = logoH * (logoData.width / logoData.height);
                doc.addImage(logoData.dataUrl, 'PNG', PAGE.margin, 12, logoW, logoH, undefined, 'FAST');
            } catch (e) {
                console.warn('[exportMomentToPDF] failed to draw logo:', e.message);
            }
        }

        cursorY = 44;
    };

    const drawTitleBlock = () => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(18);
        setText(doc, BRAND.ink);
        const title = currentMoment?.title || 'Untitled Moment';
        const titleLines = doc.splitTextToSize(title, PAGE.contentWidth);
        titleLines.forEach((line) => {
            doc.text(line, PAGE.margin, cursorY);
            cursorY += 7;
        });

        if (currentMoment?.prompt) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            setText(doc, BRAND.muted);
            doc.text(`"${currentMoment?.prompt}"`, PAGE.margin, cursorY);
            cursorY += 6;
        }

        cursorY += 4;
    };

    /* ---------- overview stat cards ---------- */

    const drawOverviewStats = () => {
        const stats = [
            { label: 'Created', value: formatDate(currentMoment?.created_at) },
            { label: 'Results Found', value: String(currentMoment?.results?.length ?? 0) },
            {
                label: 'Asset Duration',
                value: formatDuration(currentMoment?.results?.[0]?.source?.source_duration),
            },
        ];

        const gap = 4;
        const cardW = (PAGE.contentWidth - gap * (stats.length - 1)) / stats.length;
        const cardH = 18;

        ensureSpace(cardH + 6);

        stats.forEach((s, i) => {
            const x = PAGE.margin + i * (cardW + gap);
            setFill(doc, BRAND.tint);
            setDraw(doc, BRAND.border);
            doc.setLineWidth(0.2);
            doc.roundedRect(x, cursorY, cardW, cardH, 2, 2, 'FD');

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7.5);
            setText(doc, BRAND.muted);
            doc.text(s.label.toUpperCase(), x + 3, cursorY + 6);

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(10);
            setText(doc, BRAND.ink);
            doc.text(doc.splitTextToSize(s.value, cardW - 6)[0] || '—', x + 3, cursorY + 13.5);
        });
        cursorY += cardH + 10;
    };

    /* ---------- summary (from first result's source metadata, if present) ---------- */

    const metadata = currentMoment?.results?.[0]?.source?.metadata;

    const drawSummary = () => {
        const summary = metadata?.summary?.content;
        if (!summary) return;
        sectionTitle('Executive Summary');

        // trim overly long AI summaries to keep the report crisp
        const trimmed = summary.length > 1400 ? `${summary.slice(0, 1400).trim()}…` : summary;
        const paragraphs = trimmed.split('\n').filter(Boolean);

        ensureSpace(6);
        setFill(doc, BRAND.tint);
        const estLines = paragraphs.reduce((acc, p) => acc + doc.splitTextToSize(p, PAGE.contentWidth - 8).length, 0);
        const boxH = estLines * 4.6 + 8 + (paragraphs.length - 1) * 2;
        doc.roundedRect(PAGE.margin, cursorY, PAGE.contentWidth, Math.min(boxH, 200), 2, 2, 'F');
        setFill(doc, BRAND.primary300);
        doc.rect(PAGE.margin, cursorY, 1.2, Math.min(boxH, 200), 'F');

        cursorY += 4;
        paragraphs.forEach((p) => bodyText(p, { x: PAGE.margin + 4, width: PAGE.contentWidth - 8 }));
        cursorY += 6;
    };

    /* ---------- keywords as chips ---------- */

    const drawKeywords = () => {
        const keywords = metadata?.keywords?.content;
        if (!keywords?.length) return;
        sectionTitle('Keywords');

        let x = PAGE.margin;
        const rowH = 8;
        ensureSpace(rowH);
        keywords.forEach((k) => {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(8);
            const w = doc.getTextWidth(k.keyword) + 6;
            if (x + w > PAGE.margin + PAGE.contentWidth) {
                x = PAGE.margin;
                cursorY += rowH;
                ensureSpace(rowH);
            }
            pill(k.keyword, x, cursorY, { bg: BRAND.primary100, fg: BRAND.ink });
            x += w + 2.5;
        });
        cursorY += rowH + 6;
    };

    /* ---------- highlights / chapters timeline ---------- */

    const drawTimeline = () => {
        const items = metadata?.highlights?.content || metadata?.chapters?.content;
        if (!items?.length) return;
        sectionTitle(metadata?.highlights ? 'Highlights Timeline' : 'Chapters');

        items.forEach((item, idx) => {
            const contentLines = doc.splitTextToSize(item.content, PAGE.contentWidth - 16);
            const blockH = 6 + contentLines.length * 4.2 + 4;
            ensureSpace(blockH);

            const dotY = cursorY + 2;
            setFill(doc, BRAND.primary300);
            doc.circle(PAGE.margin + 1.5, dotY, 1.5, 'F');
            if (idx < items.length - 1) {
                setDraw(doc, BRAND.border);
                doc.setLineWidth(0.4);
                doc.line(PAGE.margin + 1.5, dotY + 1.5, PAGE.margin + 1.5, dotY + blockH);
            }

            const textX = PAGE.margin + 7;
            const timeLabel = Array.isArray(item.timestamp) ? item.timestamp.join(' – ') : item.timestamp || '';

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9.5);
            setText(doc, BRAND.ink);
            doc.text(item.title || `Segment ${idx + 1}`, textX, cursorY + 3);

            if (timeLabel) {
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(8);
                setText(doc, BRAND.primary300);
                doc.text(timeLabel, PAGE.width - PAGE.margin, cursorY + 3, { align: 'right' });
            }

            cursorY += 6;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            setText(doc, BRAND.body);
            contentLines.forEach((line) => {
                ensureSpace(4.2);
                doc.text(line, textX, cursorY);
                cursorY += 4.2;
            });
            cursorY += 4;
        });
        cursorY += 2;
    };

    /* ---------- detected moments / search results ---------- */

    const drawResults = () => {
        const results = currentMoment?.results;
        if (!results?.length) return;
        sectionTitle(`Detected Moments (${results.length})`);

        results.forEach((r, idx) => {
            const lines = doc.splitTextToSize(r.context || '', PAGE.contentWidth - 8);
            const cardH = 8 + lines.length * 4.2 + 6;
            ensureSpace(cardH);

            setDraw(doc, BRAND.border);
            setFill(doc, BRAND.white);
            doc.setLineWidth(0.2);
            doc.roundedRect(PAGE.margin, cursorY, PAGE.contentWidth, cardH, 2, 2, 'FD');

            const badgeW = pill(r.timestampText || r.timestamp || `#${idx + 1}`, PAGE.margin + 3, cursorY + 3, {
                bg: BRAND.primary300,
                fg: BRAND.white,
                fontSize: 7.5,
            });

            if (r.source?.source_path) {
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(7.5);
                setText(doc, BRAND.muted);
                doc.text(r.source.source_path, PAGE.margin + 3 + badgeW + 3, cursorY + 7.2);
            }

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            setText(doc, BRAND.body);
            let ly = cursorY + 13;
            lines.forEach((line) => {
                doc.text(line, PAGE.margin + 4, ly);
                ly += 4.2;
            });

            cursorY += cardH + 4;
        });
        cursorY += 2;
    };

    /* ---------- transcription ---------- */

    const drawTranscription = () => {
        const chunks = metadata?.transcription?.content;
        if (!chunks?.length) return;
        sectionTitle('Transcript');

        chunks.forEach((c) => {
            const lines = doc.splitTextToSize(c.content, PAGE.contentWidth - 10);
            const blockH = 6 + lines.length * 4.2 + 4;
            ensureSpace(blockH);

            setFill(doc, BRAND.tint);
            doc.roundedRect(PAGE.margin, cursorY, PAGE.contentWidth, blockH, 2, 2, 'F');

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(7.5);
            setText(doc, BRAND.primary300);
            doc.text(`${c.start_time} — ${c.end_time}`, PAGE.margin + 4, cursorY + 5);

            doc.setFont('helvetica', 'italic');
            doc.setFontSize(9);
            setText(doc, BRAND.body);
            let ly = cursorY + 10;
            lines.forEach((line) => {
                doc.text(line, PAGE.margin + 4, ly);
                ly += 4.2;
            });

            cursorY += blockH + 4;
        });
    };

    /* ---------- assemble ---------- */

    drawCoverHeader();
    drawTitleBlock();
    drawOverviewStats();
    drawSummary();
    drawKeywords();
    drawTimeline();
    drawResults();
    drawTranscription();
    drawFooter();

    const outName =
        fileName || `${(currentMoment?.title || 'moment').trim().replace(/\s+/g, '-').toLowerCase()}-report.pdf`;
    doc.save(outName);
    return doc;
}

/* ------------------------------------------------------------------ */
/* Ready-to-drop-in export button                                      */
/* ------------------------------------------------------------------ */

export function ExportPdfButton({ currentMoment, logoPath = '/new-crips-ai-logo-black-resize.png', appName = 'CrispAI' }) {
    const [loading, setLoading] = useState(false);

    const handleClick = async () => {
        if (!currentMoment || loading) return;
        setLoading(true);
        try {
            await exportMomentToPDF(currentMoment, { logoPath, appName });
        } catch (err) {
            console.error('PDF export failed:', err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <RippleButton
            cssClasses={`px-2 flex items-center gap-1 py-2 text-sm rounded ${loading ? 'cursor-default' : 'cursor-pointer'}`}
            disabled={loading}
            onClick={handleClick}
        >
            {loading ? 'Generating PDF…' : 'Export as PDF'}
        </RippleButton>
    );
}

export default exportMomentToPDF;
