import { jsPDF } from 'jspdf';
import React, { useState } from 'react';
import {
    FileDown
} from "lucide-react";
import {
    BRAND,
    PAGE,
    setFill,
    setText,
    setDraw,
    loadImageAsDataURL,
    formatDuration,
} from '../../utils/pdfReportHelpers';
import RippleButton from '../RippleButton';

/* ------------------------------------------------------------------ */
/* PDF builder                                                         */
/* ------------------------------------------------------------------ */

export async function exportAssetMetadataToPDF(asset, options = {}) {
    const { logoPath = '/new-crips-ai-logo-black-resize.png', appName = 'CrispAI', fileName } = options;

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    let cursorY = 0;
    let page = 1;

    let logoData = null;
    try {
        logoData = await loadImageAsDataURL(logoPath);
    } catch (err) {
        console.warn('[exportAssetMetadataToPDF] logo not loaded:', err.message);
    }

    const drawFooter = () => {
        setDraw(doc, BRAND.border);
        doc.setLineWidth(0.2);
        doc.line(PAGE.margin, PAGE.height - 14, PAGE.width - PAGE.margin, PAGE.height - 14);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        setText(doc, BRAND.muted);
        doc.text(`Generated by ${appName}`, PAGE.margin, PAGE.height - 9);
        doc.text(`Page ${page}`, PAGE.width - PAGE.margin, PAGE.height - 9, { align: 'right' });
    };

    const newPage = () => {
        drawFooter();
        doc.addPage();
        page += 1;
        cursorY = PAGE.margin;
    };

    const ensureSpace = (h) => {
        if (cursorY + h > PAGE.height - 20) newPage();
    };

    const sectionTitle = (label) => {
        ensureSpace(12);
        setFill(doc, BRAND.primary300);
        doc.roundedRect(PAGE.margin, cursorY, 1.4, 5, 0.7, 0.7, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        setText(doc, BRAND.ink);
        doc.text(label.toUpperCase(), PAGE.margin + 4, cursorY + 4.2);
        cursorY += 10;
    };

    const pill = (text, x, y, { bg = BRAND.tint, fg = BRAND.primary300, fontSize = 8 } = {}) => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(fontSize);
        const padX = 3;
        const w = doc.getTextWidth(text) + padX * 2;
        const h = 6;
        setFill(doc, bg);
        doc.roundedRect(x, y, w, h, h / 2, h / 2, 'F');
        setText(doc, fg);
        doc.text(text, x + padX, y + h / 2 + 1.4);
        return w;
    };

    /* ---------- header ---------- */

    const drawHeader = () => {
        setFill(doc, BRAND.primary300);
        doc.rect(0, 0, PAGE.width, 34, 'F');
        setFill(doc, BRAND.primary200);
        doc.triangle(PAGE.width * 0.55, 0, PAGE.width, 0, PAGE.width, 34, 'F');

        let logoOffsetX = PAGE.margin;
        if (logoData) {
            try {
                const logoH = 10;
                const logoW = logoH * (logoData.width / logoData.height);
                doc.addImage(logoData.dataUrl, 'PNG', PAGE.margin, 12, logoW, logoH, undefined, 'FAST');
                logoOffsetX = PAGE.margin + logoW + 4;
            } catch (e) {
                console.warn('[exportAssetMetadataToPDF] failed to draw logo:', e.message);
            }
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        setText(doc, BRAND.white);
        doc.text('AI VIDEO ASSET REPORT', logoOffsetX, 17.5);

        cursorY = 44;
    };

    const drawTitleBlock = () => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(18);
        setText(doc, BRAND.ink);
        const title = asset.source_path || asset.source_id || 'Untitled Asset';
        doc.splitTextToSize(title, PAGE.contentWidth).forEach((line) => {
            doc.text(line, PAGE.margin, cursorY);
            cursorY += 7;
        });

        if (asset.metadata?.summary?.title) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            setText(doc, BRAND.muted);
            doc.text(asset.metadata.summary.title, PAGE.margin, cursorY);
            cursorY += 6;
        }
        cursorY += 4;
    };

    const drawOverviewStats = () => {
        const stats = [
            { label: 'Duration', value: formatDuration(asset.source_duration) },
            { label: 'Language', value: (asset.originalSourceLanguage || '—').toUpperCase() },
            { label: 'Keywords', value: String(asset.metadata?.keywords?.content?.length ?? 0) },
            { label: 'Chapters', value: String(asset.metadata?.chapters?.content?.length ?? 0) },
        ];
        const gap = 4;
        const cardW = (PAGE.contentWidth - gap * (stats.length - 1)) / stats.length;
        const cardH = 18;

        ensureSpace(cardH + 6);
        stats.forEach((s, i) => {
            const x = PAGE.margin + i * (cardW + gap);
            setFill(doc, BRAND.tint);
            setDraw(doc, BRAND.border);
            doc.setLineWidth(0.2);
            doc.roundedRect(x, cursorY, cardW, cardH, 2, 2, 'FD');
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7.5);
            setText(doc, BRAND.muted);
            doc.text(s.label.toUpperCase(), x + 3, cursorY + 6);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(10);
            setText(doc, BRAND.ink);
            doc.text(doc.splitTextToSize(s.value, cardW - 6)[0] || '—', x + 3, cursorY + 13.5);
        });
        cursorY += cardH + 10;
    };

    /* ---------- summary ---------- */

    const drawSummary = () => {
        const summary = asset.metadata?.summary?.content;
        if (!summary) return;
        sectionTitle('Executive Summary');

        const trimmed = summary.length > 1400 ? `${summary.slice(0, 1400).trim()}…` : summary;
        const paragraphs = trimmed.split('\n').filter(Boolean);

        ensureSpace(6);
        const estLines = paragraphs.reduce((acc, p) => acc + doc.splitTextToSize(p, PAGE.contentWidth - 8).length, 0);
        const boxH = Math.min(estLines * 4.6 + 8 + (paragraphs.length - 1) * 2, 200);
        setFill(doc, BRAND.tint);
        doc.roundedRect(PAGE.margin, cursorY, PAGE.contentWidth, boxH, 2, 2, 'F');
        setFill(doc, BRAND.primary300);
        doc.rect(PAGE.margin, cursorY, 1.2, boxH, 'F');

        cursorY += 4;
        paragraphs.forEach((p) => {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9.5);
            setText(doc, BRAND.body);
            doc.splitTextToSize(p, PAGE.contentWidth - 8).forEach((line) => {
                ensureSpace(4.6);
                doc.text(line, PAGE.margin + 4, cursorY + 3.2);
                cursorY += 4.6;
            });
        });
        cursorY += 6;
    };

    /* ---------- keywords ---------- */

    const drawKeywords = () => {
        const keywords = asset.metadata?.keywords?.content;
        if (!keywords?.length) return;
        sectionTitle('Keywords');

        let x = PAGE.margin;
        const rowH = 8;
        ensureSpace(rowH);
        keywords.forEach((k) => {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(8);
            const w = doc.getTextWidth(k.keyword) + 6;
            if (x + w > PAGE.margin + PAGE.contentWidth) {
                x = PAGE.margin;
                cursorY += rowH;
                ensureSpace(rowH);
            }
            pill(k.keyword, x, cursorY, { bg: BRAND.primary100, fg: BRAND.ink });
            x += w + 2.5;
        });
        cursorY += rowH + 6;
    };

    /* ---------- chapters / highlights timeline ---------- */

    const drawTimelineSection = (label, items) => {
        if (!items?.length) return;
        sectionTitle(label);

        items.forEach((item, idx) => {
            const contentLines = doc.splitTextToSize(item.content, PAGE.contentWidth - 16);
            const blockH = 6 + contentLines.length * 4.2 + 4;
            ensureSpace(blockH);

            const dotY = cursorY + 2;
            setFill(doc, BRAND.primary300);
            doc.circle(PAGE.margin + 1.5, dotY, 1.5, 'F');
            if (idx < items.length - 1) {
                setDraw(doc, BRAND.border);
                doc.setLineWidth(0.4);
                doc.line(PAGE.margin + 1.5, dotY + 1.5, PAGE.margin + 1.5, dotY + blockH);
            }

            const textX = PAGE.margin + 7;
            const timeLabel = Array.isArray(item.timestamp) ? item.timestamp.join(' – ') : item.timestamp || '';

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9.5);
            setText(doc, BRAND.ink);
            doc.text(item.title || `Segment ${idx + 1}`, textX, cursorY + 3);

            if (timeLabel) {
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(8);
                setText(doc, BRAND.primary300);
                doc.text(timeLabel, PAGE.width - PAGE.margin, cursorY + 3, { align: 'right' });
            }

            cursorY += 6;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            setText(doc, BRAND.body);
            contentLines.forEach((line) => {
                ensureSpace(4.2);
                doc.text(line, textX, cursorY);
                cursorY += 4.2;
            });
            cursorY += 4;
        });
        cursorY += 2;
    };

    /* ---------- FAQs ---------- */

    const drawFaqs = () => {
        const faqs = asset.metadata?.faqs?.content;
        if (!faqs?.length) return;
        sectionTitle('Frequently Asked Questions');

        faqs.forEach((faq) => {
            const qLines = doc.splitTextToSize(faq.question, PAGE.contentWidth - 8);
            const aLines = doc.splitTextToSize(faq.answer, PAGE.contentWidth - 8);
            const blockH = qLines.length * 4.6 + aLines.length * 4.4 + 10;
            ensureSpace(blockH);

            setDraw(doc, BRAND.border);
            setFill(doc, BRAND.white);
            doc.setLineWidth(0.2);
            doc.roundedRect(PAGE.margin, cursorY, PAGE.contentWidth, blockH, 2, 2, 'FD');

            let ly = cursorY + 6;
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9.5);
            setText(doc, BRAND.primary300);
            qLines.forEach((line) => {
                doc.text(`Q. ${line}`, PAGE.margin + 4, ly);
                ly += 4.6;
            });

            ly += 1;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            setText(doc, BRAND.body);
            aLines.forEach((line) => {
                doc.text(line, PAGE.margin + 4, ly);
                ly += 4.4;
            });

            cursorY += blockH + 4;
        });
    };

    /* ---------- transcription ---------- */

    const drawTranscription = () => {
        const chunks = asset.metadata?.transcription?.content;
        if (!chunks?.length) return;
        sectionTitle('Transcript');

        chunks.forEach((c) => {
            const lines = doc.splitTextToSize(c.content, PAGE.contentWidth - 10);
            const blockH = 6 + lines.length * 4.2 + 4;
            ensureSpace(blockH);

            setFill(doc, BRAND.tint);
            doc.roundedRect(PAGE.margin, cursorY, PAGE.contentWidth, blockH, 2, 2, 'F');

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(7.5);
            setText(doc, BRAND.primary300);
            doc.text(`${c.start_time} — ${c.end_time}`, PAGE.margin + 4, cursorY + 5);

            doc.setFont('helvetica', 'italic');
            doc.setFontSize(9);
            setText(doc, BRAND.body);
            let ly = cursorY + 10;
            lines.forEach((line) => {
                doc.text(line, PAGE.margin + 4, ly);
                ly += 4.2;
            });

            cursorY += blockH + 4;
        });
    };

    /* ---------- assemble ---------- */

    drawHeader();
    drawTitleBlock();
    drawOverviewStats();
    drawSummary();
    drawKeywords();
    drawTimelineSection(
        asset.metadata?.chapters ? 'Chapters' : 'Highlights',
        asset.metadata?.chapters?.content || asset.metadata?.highlights?.content
    );
    if (asset.metadata?.chapters && asset.metadata?.highlights) {
        drawTimelineSection('Highlights', asset.metadata.highlights.content);
    }
    drawFaqs();
    drawTranscription();
    drawFooter();

    const outName =
        fileName || `${(asset.source_path || asset.source_id || 'asset').replace(/\s+/g, '-').toLowerCase()}-metadata.pdf`;
    doc.save(outName);
    return doc;
}

/* ------------------------------------------------------------------ */
/* Ready-to-drop-in export button                                      */
/* ------------------------------------------------------------------ */

export function ExportAssetPdfButton({ asset, logoPath = '/new-crips-ai-logo-black-resize.png', appName = 'CrispAI', className = '' }) {
    const [loading, setLoading] = useState(false);

    const handleClick = async () => {
        if (!asset || loading) return;
        setLoading(true);
        try {
            await exportAssetMetadataToPDF(asset, { logoPath, appName });
        } catch (err) {
            console.error('PDF export failed:', err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <RippleButton
            cssClasses="shrink-0 flex items-center gap-1 disabled:cursor-not-allowed p-2"
            disabled={loading}
            onClick={handleClick}
        >
            <FileDown size={14} className={loading ? "animate-customPulse" : ""} />
            <span className={`text-sm ${loading ? "animate-customPulse" : ""}`}>
                {loading ? "Exporting…" : "Export metadata as PDF"}
            </span>
        </RippleButton>
    );
}

export default exportAssetMetadataToPDF;